[package]
name = "ollama-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
ollama-rs = "0.3.1"
tokio = { version = "1.45.0", features = ["full"] }
regex = "1.11.1"
iced = "0.13.1"
iced_widget = { version = "0.13", features = ["markdown"] }
futures = "0.3.31"
iced_native = "0.10.3"
webbrowser = "1.0.4"