[package]
name = "ollama-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
ollama-rs = { version = "0.3.1", features = ["stream"] }
tokio = { version = "1.45.0", features = ["full"] }
regex = "1.11.1"
iced = "0.13.1"
iced_widget = { version = "0.13", features = ["markdown"] }
futures = "0.3.31"
iced_native = "0.10.3"
webbrowser = "1.0.4"
crossbeam-channel = "0.5.15"
lazy_static = "x"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde_json = "1.0.140" 