[package]
name = "ollama-gui"
version = "0.1.3"
edition = "2024"

[dependencies]
ollama-rs = { version = "0.3.1", features = ["stream"] }
tokio = { version = "1.45.1", features = ["full"] }
regex = "1.11.1"
iced = "0.13.1"
iced_widget = { version = "0.13.4", features = ["markdown"] }
futures = "0.3.31"
iced_native = "0.10.3"
webbrowser = "1.0.4"
crossbeam-channel = "0.5.15"
lazy_static = "1.5.0"
reqwest = { version = "0.12.16", features = ["blocking", "json"] }
serde_json = "1.0.140" 
rustrict = "0.7.35"

[profile.release]
opt-level = 2
lto = "thin"